name: "TestU01"
run-name: "TestU01 ${{inputs.bbattery_TestName}} battery run with ${{inputs.generator_name}}"

on:
  workflow_dispatch:
    inputs:
      bbattery_TestName:
        description: >
          Predefined batteries of statistical tests
        required: true
        default: 'SmallCrush'
        type: choice
        options: ['SmallCrush', 'Crush', 'BigCrush', 'FIPS_140_2', 'PseudoDIEHARD']
      generator_name:
        description: >
          Pseudo Random Number Generator
        required: true
        default: '10'
        type: choice
        options: ['AKalashnikovaChaCha20', 'AKalashnikovaXChaCha20', 'AKalashnikovaChaCha20_', 'AKalashnikovaGaloisLeftLFSR', 'AKalashnikovaGaloisRightLFSR']

env:
  TEST_NUM: "10"
  DIR_NAME: "AKalashnikovaFibonacciLFSR"

jobs:
  prepare:
    name: Set parameters
    runs-on: ubuntu-latest
    outputs:
      test_num: ${{ env.TEST_NUM }}
      test_dir: ${{ env.DIR_NAME }}
    steps:
    - name: Echo ENV parameters
      run: echo ${{ github.events.inputs.environment }}

  main:
    name: Run test with the parameters
    uses: ./.github/workflows/reusable_lfsr_generator.yml
    needs: prepare
    with:
      test_num: ${{needs.prepare.outputs.test_num}}
      test_dir: ${{needs.prepare.outputs.test_dir}}
      bbattery_TestName: ${{inputs.bbattery_TestName}}
      generator_name: ${{inputs.generator_name}}
